image: node:15-alpine

stages:
  - lint
  - build
  - publish-to-s3

cache:
  paths:
    - node_modules/
  untracked: true

before_script:
  - yarn install --frozen-lockfile

lint:
  stage: lint
  script:
    - yarn lint

build:
  stage: build
  only:
    - tags
  script:
    - CI=false
    - yarn build
    - CI=true
  artifacts:
    untracked: false
    paths:
      - build/

publish-to-s3:
  image: python:latest
  stage: publish-to-s3
  dependencies:
    - build
  only:
      - tags
  before_script:
    - pip install awscli
  script:
    - aws s3 sync ./build s3://barboss --delete
